# Setup
title:            Joseph Whiting
permalink:        pretty
tagline:          'Software Developer'
description:      'Functional Programming, Reactive Programming, Scala, Machine Learning, GraphQL'
baseurl:          'https://joseph-whiting.github.io'

author:
  name:           'Joseph Whiting'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

paginate:         5

# Custom vars
version:          2.1.0

plugins: [jekyll-paginate, jekyll-gist]
