# Dependencies
markdown:         redcarpet  

# Permalinks
permalink:        pretty

# Setup
title:            Joseph Whiting
tagline:          'Software Developer'
description:      'Functional Programming, Reactive Programming, Scala, Machine Learning, GraphQL'
baseurl:          /

author:
  name:           'Joseph Whiting'

paginate:         5

# Custom vars
version:          2.1.0

plugins: [jekyll-paginate, jekyll-gist]
